build: Generate Tasks & CI Config (#338)
Co-authored-by: Tedium <tedium-markormesher[bot]@users.noreply.github.com>

diff --git a/taskfile.yml b/taskfile.yml
--- a/taskfile.yml
+++ b/taskfile.yml
@@ -8,26 +8,123 @@ includes:
 tasks:
   cachekey:
     cmds:
-      - cmd: rm -f "{{.ROOT_DIR}}/.task-meta-cachekey"*
-      - task: cachekey-go-root
-  cachekey-go:
+      - task: cachekey-root-go
+  cachekey-root:
     cmds:
-      - task: cachekey-go-root
-  cachekey-go-root:
+      - task: cachekey-root-go
+  cachekey-root-go:
     dir: '{{.ROOT_DIR}}'
+    generates:
+      - .task-meta-cache-key
     cmds:
-      - cmd: sha256sum go.mod | awk '{print $1}' >> "{{.ROOT_DIR}}/.task-meta-cachekey-go"
-      - cmd: if [[ -f go.sum ]]; then sha256sum go.sum | awk '{print $1}' >> "{{.ROOT_DIR}}/.task-meta-cachekey-go"; fi
+      - cmd: |-
+          if [[ -n ${CI:-} ]]; then
+            if [[ -n ${FORGEJO_REPOSITORY:-} ]]; then
+              PROJECT=$(echo "$FORGEJO_REPOSITORY" | tr -dc '[[a-z0-9]]')
+            elif [[ -n ${GITHUB_REPOSITORY:-} ]]; then
+              PROJECT=$(echo "$GITHUB_REPOSITORY" | tr -dc '[[a-z0-9]]')
+            else
+              PROJECT="noproject"
+            fi
+
+            DEPS_SHA=$(cat go.mod | sha256sum | awk '{ print $1 }')
+
+            if [[ -f go.sum ]]; then
+              LOCK_SHA=$(cat go.sum | sha256sum | awk '{ print $1 }')
+            else
+              LOCK_SHA="nolock"
+            fi
+
+            echo "${PROJECT}-go-v1/${DEPS_SHA}/${LOCK_SHA}" > .task-meta-cache-key
+          fi
+  cacheload:
+    cmds:
+      - task: cacheload-root-go
+  cacheload-root:
+    cmds:
+      - task: cacheload-root-go
+  cacheload-root-go:
+    dir: '{{.ROOT_DIR}}'
+    deps:
+      - cachekey-root-go
+    cmds:
+      - cmd: |-
+          if [[ -n "${CI_CACHE_TOKEN:-}" ]] && [[ -f ".task-meta-cache-key" ]]; then
+            request_key=$(cat ".task-meta-cache-key" | tr -d '\r\n')
+            start_ts=$(date +%s)
+            header_file=$(mktemp)
+            cache_file=$(mktemp)
+
+            echo "loading cache..."
+            echo "request key: ${request_key}"
+            if curl -fsSL -D "${header_file}" -H "authorization: Bearer ${CI_CACHE_TOKEN}" "https://ci-cache.markormesher.co.uk/cache/${request_key}" -o "${cache_file}"; then
+              actual_key=$(cat "${header_file}" | grep -i x-cache-key | cut -d ' ' -f 2 | tr -d '\r\n')
+              size=$(du -h "${cache_file}" | awk '{ print $1 }')
+              echo "received key: ${actual_key}"
+              echo "received size: ${size}"
+
+              if [[ "${actual_key}" == "${request_key}" ]]; then
+                touch .task-meta-cache-exact-match
+              fi
+
+              echo "unpacking cache..."
+              tar xzP -f "${cache_file}" || true
+            else
+              echo "no cache loaded"
+            fi
+
+            rm -f "${cache_file}" "${header_file}"
+            end_ts=$(date +%s)
+            echo "loading cache took $(( $end_ts - $start_ts ))s"
+          fi
+  cachesave:
+    cmds:
+      - task: cachesave-root-go
+  cachesave-root:
+    cmds:
+      - task: cachesave-root-go
+  cachesave-root-go:
+    dir: '{{.ROOT_DIR}}'
+    deps:
+      - cachekey-root-go
+    cmds:
+      - cmd: echo "$(go env GOMODCACHE) $(go env GOCACHE)" > .task-meta-cache-paths
+      - cmd: |-
+          if [[ -n "${CI_CACHE_TOKEN:-}" ]] && [[ -f ".task-meta-cache-key" ]]; then
+            if [[ -f .task-meta-cache-exact-match ]]; then
+              echo "skipping re-upload because an exact match was returned from the cache"
+              exit 0
+            fi
+
+            request_key=$(cat ".task-meta-cache-key")
+            start_ts=$(date +%s)
+            cache_file=$(mktemp)
+
+            echo "packing cache..."
+            tar czP -f "${cache_file}" $(cat .task-meta-cache-paths)
+            size=$(du -h "${cache_file}" | awk '{ print $1 }')
+
+            echo "uploading cache (${size})..."
+            if curl -fsSL -H "authorization: Bearer ${CI_CACHE_TOKEN}" -X PUT "https://ci-cache.markormesher.co.uk/cache/${request_key}" --data-binary "@${cache_file}"; then
+              echo "uploaded cache"
+            else
+              echo "error saving cache"
+            fi
+
+            rm -f "${cache_file}"
+            end_ts=$(date +%s)
+            echo "saving cache took $(( $end_ts - $start_ts ))s"
+          fi
   deps:
     cmds:
-      - task: deps-go-root
-  deps-go:
+      - task: deps-root-go
+  deps-root:
     cmds:
-      - task: deps-go-root
-  deps-go-root:
+      - task: deps-root-go
+  deps-root-go:
     dir: '{{.ROOT_DIR}}'
     cmds:
-      - cmd: go mod tidy && go mod download --json
+      - cmd: go mod download
       - cmd: (go tool || true) | (grep '\.' || true) | while read t; do go build -o /dev/null $t; done
   imgbuild:
     cmds:
@@ -166,11 +263,11 @@ tasks:
           cat .task-meta-imgrefs | grep "." || echo "None"
   lint:
     cmds:
-      - task: lint-go-root
-  lint-go:
+      - task: lint-root-go
+  lint-root:
     cmds:
-      - task: lint-go-root
-  lint-go-root:
+      - task: lint-root-go
+  lint-root-go:
     dir: '{{.ROOT_DIR}}'
     cmds:
       - cmd: |-
@@ -207,11 +304,11 @@ tasks:
           exit $exit_code
   lintfix:
     cmds:
-      - task: lintfix-go-root
-  lintfix-go:
+      - task: lintfix-root-go
+  lintfix-root:
     cmds:
-      - task: lintfix-go-root
-  lintfix-go-root:
+      - task: lintfix-root-go
+  lintfix-root-go:
     dir: '{{.ROOT_DIR}}'
     cmds:
       - cmd: gofmt -s -w .
